### ISSUE TITLE
Drag & drop support - resize dialog window for selecting file - column view - resizable & movable columns

### ISSUE THREAD

**Issue by ihubgit** [Jacalz/rymdport#101]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Ok this are suggestions for better comfort for the end user :

1. current implementation of file selection is quite cumbersome : small and unresizable dialog box, no drag and drop, no column view
2. in the send/receive window, no way to rearrange size of the columns nor to move them

### Describe the solution you'd like to see.

1. it would be nice to be able to simply drag and drop a document or file on the main window rather than having to delve into the OS's file bowels to find the file.
- when do using the dialog box for looking for the file, being able to resize it would make navigation easier
-having an optional column view of that dialog box would also facilitate navigation

2. maybe show visible handles between the different columns (text field / code / progress bar) allowing for both resizing them (the code always eats into the progress bar by default) and also to move them or optionnally hide according to the likes of the end user

**Comment by Jacalz** [comment]
Thanks but please keep issues to one request per issue. I will close this and you are free to divide it up into more issues as you see fit but please read my notes below first:
- I can not do anything about the file dialog in this project. It is the file dialog from https://github.com/fyne-io/fyne that I am using. If you have suggestions for improving it, please open an issue (or multiple depending on how related they are) there instead (but verify that there isn't a duplicate already).
- Drag and drop support has already been added with https://github.com/Jacalz/rymdport/issues/73. It will be in the next release.
- Eating up the progress bar is tracked in https://github.com/Jacalz/rymdport/issues/96 already.
