### ISSUE TITLE
ability to resize the open file dialog box

### ISSUE THREAD

**Issue by ihubgit** [Jacalz/rymdport#102]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

the open file dialog box has a fixed width and is too small to easily visualize and navigate thru the file structure of the OS

### Describe the solution you'd like to see.

The ability to resize it, f.ex. by simply dragging out the corners (or even just the bottom ones) would make navigation a lot more confortable.
I don't know whether this feature is limited by Fine.io or not but if so I'll gladly open an issue there.

**Comment by Jacalz** [comment]
Thanks for opening the issue. I absolutely agree with you that this would be very useful. Like you hinted at, this is indeed a limitation upstream in Fyne. There is an open issue for it there:  https://github.com/fyne-io/fyne/issues/3917
Closing this as a duplicate
