### ISSUE TITLE
Support for Tor onion services

### ISSUE THREAD

**Issue by ihubgit** [Jacalz/rymdport#103]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

current implementation of Wormhole is over the Clearnet, especially the relay server part, which may be considered not sufficiently satisfactory in some user settings.

### Describe the solution you'd like to see.

[http://www.lothar.com/~warner/MagicWormhole-PyCon2016.pdf](url)

From the 2016 presentation it seems Tor onion support was in the pipeline.
As Rymdport is a full fledged implementation of Wormhole, it would be a bonus to be able to integrate Tor onion services in the file sharing protocol.

**Comment by Jacalz** [comment]
I'm afraid that this also happens to be an upstream issue. The wormhole protocol support is implemented in the `wormhole-William` package. There is an open issue for Tor support over at https://github.com/psanford/wormhole-william/issues/45.

I feel a bit sorry for you having multiple issues closed like this in a rapid succession. I don't want you to get the wrong end of the stick here, I very much appreciate your ideas and opinions regardless :)
