### ISSUE TITLE
Add a way to send using custom code when dropping files/folders

### ISSUE THREAD

**Issue by Jacalz** [Jacalz/rymdport#108]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The (upcoming) v3.5.0 release adds support for dropping file and folders onto the window but there is currently no way to use custom codes for the send.

### Describe the solution you'd like to see.

We need to think of a good way to make it possible to specify using custom codes when dropping files. How to expose that is a good question.

**Comment by GalihFajar** [comment]
Hi @Jacalz I've made a draft PR to address this issue. Made it as a draft because it's still an idea (+ contains no new added tests). Please find the PR description to see how it works. 

Thanks.

**Comment by Jacalz** [comment]
Thanks @GalihFajar. I appreciate you taking the time to contribute. I'll have a look later today

PS: You can probably skip the tests if you want. I haven't quite set up a good plan for how I want to handle tests for the backend. I suppose some code might have to be refactored to be more easily testable.

**Comment by Jacalz** [comment]
Thanks @GalihFajar. This is now solved.
