### ISSUE TITLE
Ability to queue shares and not simultaneous downloads

### ISSUE THREAD

**Issue by ihubgit** [Jacalz/rymdport#110]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

So have been doing some testing with sharing multiple files, dropped individually in the window, at once and sharing their individual codes to the recipient.
When the latter launches multiple downloads, they are all activated simultaneously, causing an overload in bandwith and failure of the downloads.
Especially getting :
TransferError : transfer rejected
write TCP ip adress:port -> idem : write : broken pipe

### Describe the solution you'd like to see.

the ability (at least the option for the end user) to be able to stack shares that will be queued for the recipient, thus allowing for only one download at once.
This ought to be automated : i.e. the first share finished, the second one automatically starts without having to manually validate by the recipient.
This allows to be away from the screen while sharing.

**Comment by Jacalz** [comment]
If you are getting errors, report that as a bug (or separate depending on what you are getting) please. I don't believe that this is the solution for your problems. I don't have any plans to add support for queuing shares or limiting to one download at a time. If you need more advanced features there is probably a better tool for the job out there.

**Comment by Jacalz** [comment]
Please open a bug report for the errors you are getting.
