### ISSUE TITLE
Build RichText segments without parsing markdown

### ISSUE THREAD

**Issue by Jacalz** [Jacalz/rymdport#117]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

For the QR-code and information dialog we are currently parsing markdown to build the text. We can set the required RichText regiments directly without having to parse a markdown string each time.

### Describe the solution you'd like to see.

Set RichText segments directly. Hopefully it means that the markdown parser is dead code eliminates leading to smaller binaries (not sure how tightly coupled it is in Fyne or how smart the Go compiler is there).

**Comment by GalihFajar** [comment]
HI, is this issue available to be taken? Might need to explore first though, but I want to give it a try. Thanks!

**Comment by Jacalz** [comment]
It is indeed available to be taken. As long as no one is assigned it is fine. However, I haven't tested that it is better than parsing markdown.

**Comment by GalihFajar** [comment]
Appreciate it, could you help assign it to me?

**Comment by GalihFajar** [comment]
I've submitted the PR [here](https://github.com/Jacalz/rymdport/pull/121).

I've built the code on the arm64 and it indeeds reduce the binaries smaller for about 2.3%.

**Comment by Jacalz** [comment]
Thanks for looking at it. I've assigned you to the issue and will try to review the PR later today :)
