### ISSUE TITLE
Pick up non-standard Windows Downloads path

### ISSUE THREAD

**Issue by stdedos** [Jacalz/rymdport#118]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

User might have a non-standard Downloads path (i.e., not `%USERPROFILE%\Downloads`)

### Describe the solution you'd like to see.

```go
package main

import (
	"fmt"
	"golang.org/x/sys/windows/registry"
)

func getDownloadsPath() (string, error) {
	k, err := registry.OpenKey(registry.CURRENT_USER, `Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders`, registry.QUERY_VALUE)
	if err != nil {
		return "", err
	}
	defer k.Close()

	downloads, _, err := k.GetStringValue("{374DE290-123F-4565-9164-39C4925E467B}")
	if err != nil {
		return "", err
	}

	return downloads, nil
}

func main() {
	path, err := getDownloadsPath()
	if err != nil {
		fmt.Println("Failed to get the Downloads path:", err)
		return
	}

	fmt.Println("Downloads path:", path)
}
```

_untested_

**Comment by Jacalz** [comment]
Thanks for opening this issue. I have thought a bit about this and I think I'll have to close this unfortunately. I'm sorry.

Rymdport is a cross-platform application and as such I really want to include as little platform specific code as possible. Given that manually setting the download path is a few clicks away in the settings I'm not sure maintaining platform specific code for this is worth it for me. My access to Windows is sporadic at best and the less that can break between releases the better.

Messing around in the registry also seems kind of dangerous and a bit like magic; especially for someone not well versed in the quirks of Windows :/
