### ISSUE TITLE
Switch to wormhole servers from Least Authority more easily

### ISSUE THREAD

**Issue by Jacalz** [Jacalz/rymdport#125]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The folk over at Least Authority have [Winden](https://github.com/LeastAuthority/winden) and [Destiny](https://github.com/LeastAuthority/destiny) as some very good clients for sending using the same Wormhole protocol. This is very useful because they allow to send and revive from a web browser and Android/iOS respectively. However, they do not use the same servers by default and a user would have to manually use these settings:

- AppID: lothar.com/wormhole/text-or-file-xfer
- Rendezvous URL: wss://mailbox.mw.leastauthority.com/v1
- Transit Relay Address: relay.mw.leastauthority.com:4001

### Describe the solution you'd like to see.

I'm thinking that we can update the advanced section to use [widget.SelectEntry{}](https://pkg.go.dev/fyne.io/fyne/v2/widget#SelectEntry) instead of [widget.Entry{}](https://pkg.go.dev/fyne.io/fyne/v2/widget#Entry) and provide the Least Authority servers as alternatives without the user having to paste them in manually (also makes it easier to switch between that and the standard settings):

![image](https://github.com/Jacalz/rymdport/assets/25466657/bf433c3b-de25-4d04-8dd6-a5ca39d4e0a8)

Even though the AppID parameter is the same, I suppose we could add only `lothar.com/wormhole/text-or-file-xfer` to the options there. I suppose it would be better to also stop putting the defaults in the placeholder text and just have them all in the options list instead.

**Comment by Jacalz** [comment]
TODO: Also update the page for supported clients according to https://magic-wormhole.readthedocs.io/en/latest/ecosystem.html#guis-for-desktop-mobile-web.

**Comment by Jacalz** [comment]
@GalihFajar Is this something you perhaps would be interested in looking at? I've tried to make the problem and solution as clear as possible :)

**Comment by GalihFajar** [comment]
@Jacalz Sure, I'd love to take a look at it. Will be slow response on the weekend though

**Comment by Jacalz** [comment]
Cool. Thanks. That's no problem at all. Take all the time you need. I'll assign you to the issue for now

**Comment by GalihFajar** [comment]
Hi @Jacalz, I've made the PR for this, but honestly I'm not quite sure whether it switches properly from the default ones. Can you help to take a look and verify? Many thanks.

**Comment by Jacalz** [comment]
Works great. Thanks :+1:
