### ISSUE TITLE
macOS arm64 app bundle 'damaged'

### ISSUE THREAD

**Issue by leechgrrl** [Jacalz/rymdport#131]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

macOS refuses to run the app bundle on my M1 Macbook Air, saying that it is "damaged" and "can't be opened."

The amd64 app bundle works fine through Rosetta 2.

### Steps to Reproduce

1. Launch arm64 macOS app bundle
2. It does not run

### Screenshots

<img width="372" alt="Screenshot 2023-12-11 at 9 53 24 am" src="https://github.com/Jacalz/rymdport/assets/58349791/0ba0fd4a-ba76-4683-bf1e-8f060a338d52">

### Rymdport version

3.5.1

### Operating System

macOS

### Operating System Version

Sonoma 14.1.2

**Comment by leechgrrl** [comment]
Uh... I'm just blind, apparently. Steps to fix are outlined in README.md. My bad

**Comment by Jacalz** [comment]
No problem. It’s a strange problem and can only be remedied by paying for signing certificates. We’ll get there one day I’m sure but it’s not happening on my student wages 🙃

**Comment by Jacalz** [comment]
Anyway, thanks for opening the issue. It’s always greatly appreciated. Have a great day 🙂
