### ISSUE TITLE
Darwin release binaries for v3.5.2 should be renamed to macOS

### ISSUE THREAD

**Issue by slrgt** [Jacalz/rymdport#133]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

It's confusing for non developer to understand that "darwin" is the mac os version.

### Describe the solution you'd like to see.

Rename the Darwin packages to say Mac or macOS

**Comment by Jacalz** [comment]
Gosh. All other releases have said macOS for years. I forgot to rename them this time. The build tool spits out that name unfortunately. I probably should write myself an automatic rename script :/

**Comment by Jacalz** [comment]
Should be fixed now. Sorry

**Comment by slrgt** [comment]
thank you!
