### ISSUE TITLE
Add support for multiple wormhole like service relays

### ISSUE THREAD

**Issue by vRobM** [Jacalz/rymdport#137]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Sucks when a transfer code from someone doesn't work as they're using different relays.

### Describe the solution you'd like to see.

Add all public relays for all similar services, like croc, wormhole clones, etc. 

If nothing else, add ability to add additional relays manually, for private relay use and cross functional transfers. 🤝

**Comment by Jacalz** [comment]
Related to https://github.com/Jacalz/rymdport/issues/80. I don't currently have any plans for Wormhole clones. What I might consider is implementing a better protocol if there is a significant improvement over the regular Wormhole protocol. Maybe https://github.com/SpatiumPortae/portal or the planned V2 wormhole protocol.

However, I don't think `croc` fits in there given that a lot of logic seems to be hard-coded into the `cli` library and the package seems very complicated and is somewhat poorly documented. I have been in discussions about it previously and I think we concluded that the most sensible solution would be to execute the cli program and that's something that I absolutely want to avoid at all costs. There should be no external dependencies required and I don't have any control of what version of croc is used in that case.

On a brighter note, https://github.com/Jacalz/rymdport/issues/125 will be included in the next release. I hope that you can consider it somewhat of an improvement for your case here.

I really do appreciate your idea but I will have to close this as out of scope for now. Sorry about that.

**Comment by Jacalz** [comment]
It's not impossible that I change my opinion here (I suppose a PR to add another service might be accepted if it doesn't add too much code complexity) but whatever new protocol is added need to provide some useful improvement over what we already have. If not, then the use can just as well use Rymdport or some other Wormhole client of their choice.
