### ISSUE TITLE
Duplicate packages in Releases page

### ISSUE THREAD

**Issue by slrgt** [Jacalz/rymdport#138]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

Seems like every release is listed twice with no obvious distinction on what the differences are
![librewolf_P5uJgogrBL](https://github.com/Jacalz/rymdport/assets/114287507/05252d11-18e1-4e92-abcc-9fccd400b130)

### Steps to Reproduce

Go to Releases

### Rymdport version

v3.5.2

### Operating System

Other (specify below)

### Operating System Version

All

**Comment by slrgt** [comment]
btw i added "not sure what vendored means" in the Additional Information section of this bug but for some reason it just says "No response"

**Comment by Jacalz** [comment]
> Seems like every release is listed twice with no obvious distinction on what the differences are

Not sure that I agree with that. One package is for `amd64` and the other one is for `arm64`. Those are two very different computer architectures. See https://github.com/Jacalz/rymdport#downloads for more information there.

The vendored download is just the source code (like you can see given that it doesn't specify a computer architecture).

**Comment by slrgt** [comment]
Oh i didn’t notice they said something different

**Comment by Jacalz** [comment]
I updated the README.ms file and added a PACKAGING.md file to clarify the vendored files.
