### ISSUE TITLE
Error during execution on Windows 11 on VM

### ISSUE THREAD

**Issue by IoSonoPiero** [Jacalz/rymdport#140]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

I downloaded and extracted the Windows version of rymdport.
When I try to execute it, I get the error in the screenshot.

### Steps to Reproduce

Uncompress the file
Execute Rymdport.exe

### Screenshots

![Schermata del 2024-02-04 19-04-54](https://github.com/Jacalz/rymdport/assets/82404704/60de0085-aaa5-4aff-8282-91d103634ea3)

### Rymdport version

3.5.2

### Operating System

Windows

### Operating System Version

Windows 11 22H2

**Comment by Jacalz** [comment]
Thanks for the report. Is this running inside a virtual machine by any chance? If not, what kind of processor and graphics card are you using?

**Comment by IoSonoPiero** [comment]
Hello!
Yes, I tried both in KVM/QEMU and Virtualbox on Linux host.
I think this application is a lifesaver for moving files from/to a VM
without sharing folders.

Il Dom 4 Feb 2024, 22:13 Jacob Alzén ***@***.***> ha scritto:

**Comment by Jacalz** [comment]
Cool. I'm glad that you enjoy the application. Running in a carryall machine, then we know what the issue is. Rymdport requires that you have OpenGL acceleration available. This usually means that you have to enable 3D acceleration in your virtual machine. That should solve things for you.

**Comment by IoSonoPiero** [comment]
No problem at all. I'll enable it and let you know!

Thanks! 😀

Il Dom 4 Feb 2024, 22:44 Jacob Alzén ***@***.***> ha scritto:

**Comment by IoSonoPiero** [comment]
It works!
![Schermata del 2024-02-05 09-31-18](https://github.com/Jacalz/rymdport/assets/82404704/5050996d-fd1e-481e-b4ee-adbbeaef28b3)

**Comment by Jacalz** [comment]
That's great to hear 👍
