### ISSUE TITLE
Fyne error: window creation error

### ISSUE THREAD

**Issue by Caelebs** [Jacalz/rymdport#151]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

I downloaded the latest version of rymdport from the release page, and the software package is rymdport-v3.5.3-windows-amd64.zip. When I tried to open it on my Windows 10 system, it prompted an error. Do I need to install certain dependencies in my environment?

### Steps to Reproduce

1. Double-click to open the package
2. A popup error occurred

### Screenshots

![image](https://github.com/Jacalz/rymdport/assets/12752710/d7cf3924-6ea6-4ec4-a99a-25fb2651cdb3)

### Rymdport version

v3.5.3-windows

### Operating System

Windows

### Operating System Version

Windows  10.0.17763

**Comment by Jacalz** [comment]
The error indicates that your graphics driver likely doesn't support a new enough version of OpenGL. Would you mind sharing what hardware you are using? Are you running in a VM?

**Comment by Jacalz** [comment]
While at it, you can try to double check that you have the latest driver if you want to.

**Comment by Caelebs** [comment]
I'm sorry I just saw the reply. Indeed, as you said, I was running in a Windows 10 environment in a virtual machine. It works fine when I run it in a normal external environment.

**Comment by Jacalz** [comment]
Enable 3D acceleration in your VM and Rymdport should be able to start.
