### ISSUE TITLE
ARM Mac version compiled malformed

### ISSUE THREAD

**Issue by spzi** [Jacalz/rymdport#167]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

This error pertains to an M1 Max mac studio

When trying to open, a simple error message pops up.

"Rymdport.app" is damaged and cannot be opened. You should move it to the trash.

### Steps to Reproduce

1. Download the arm64.app version
2. Try to open it on an m1 max mac
3. Mac tells you to trash the app.

### Screenshots

![image](https://github.com/user-attachments/assets/e412ff95-3c64-4e67-8e64-4ec72749f4be)

### Rymdport version

3.6.0

### Operating System

macOS

### Operating System Version

macOS Sequoia 15.0

**Comment by Jacalz** [comment]
Thanks for the report but this is likely not an issue or at least not something new. See https://github.com/Jacalz/rymdport#running-on-macos-arm64-m1m2 for steps to run on arm64.
