### ISSUE TITLE
Make available through Brew

### ISSUE THREAD

**Issue by BayLee4** [Jacalz/rymdport#30]
### Is your feature request related to a problem? Please describe:

Yes, currently the update process must be done manually by checking the GitHub release page.
### Describe the solution you'd like to see:

Please make wormhole-gui installable with the Brew package manager.

**Comment by Jacalz** [comment]
Thanks. This seems like a great idea. It wasn’t really something I had considered until now. I’ll need have to look at it to see how easily it can be done and maintained.

**Comment by BayLee4** [comment]
Thanks for considering this possibility, I believe the easiest way for both creating and maintaining the package would be to make it available as a `tap` : https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

Quote : "A tap is just a Git repository so you don’t have to do anything specific when making modifications, apart from committing and pushing your changes."

**Comment by Jacalz** [comment]
Thanks. That sounds very promising as I am doing all my development from Linux. I'll have to check it out when the studies slow down a little in pace.

**Comment by Jacalz** [comment]
I have not quite had time to look at implementing this. However, the next release (v3.3.0), will contain support for automatic updates of the application. With that support added, see https://github.com/Jacalz/rymdport/issues/51, I think the use case for this issue might be partially solved :)

**Comment by BayLee4** [comment]
Well for my use case, it is _completely_ solved :) Thank you @Jacalz and congrats for the upcoming release

**Comment by Jacalz** [comment]
Thanks. That's good to hear. I think I will close this then as I think it might be good to avoid adding more maintenance burden.

If anyone is interested in publishing the application in Brew, they are more than welcome to do so :)
