### ISSUE TITLE
v3.0.0 shows command prompt (v2.2.2 does not)

### ISSUE THREAD

**Issue by duckinator** [Jacalz/rymdport#34]
### Description:

On Windows 10, Rymdport v3.0.0 shows a command prompt when running. v2.2.2 did not do this.

This isn't a huge thing, and definitely not high-priority, but I suspect it's not intentional since the command prompt doesn't actually _do_ anything. (It doesn't even print text.)

### Steps to Reproduce:

1. Start Rymdport v3.0.0 on Windows 10.

### Screenshots:

![image](https://user-images.githubusercontent.com/39698/159177884-9589710c-ffcb-42eb-ab8c-aaab843ef1db.png)

### Device (please complete the following information):
 - **OS:**  Windows
 - **Version:**  10

**Comment by duckinator** [comment]
Also, Rymdport is wonderful and has made it so much more practical to _actually use_ Wormhole. So thank you very, very much for all the time you've put into it &mdash; it's definitely appreciated!

**Comment by Jacalz** [comment]
Thanks a lot for the kind words and for opening the issue :)

I'll make sure to get this fixed for v3.0.1. This might be a bug in [fyne-cross](https://github.com/fyne-io/fyne-cross) as I don't think anything has changed, in this project, that should lead to this.

**Comment by Jacalz** [comment]
I see that you were a bit confused (and rightfully so) with the device fields at the bottom of the issue template. I think https://github.com/Jacalz/rymdport/commit/f37c98d5bf498943689ff4758e02648a6032ac31 should make it a bit clearer. The template had a leftover from the old name and a field that didn't make sense for anyone that isn't developing locally.

**Comment by Jacalz** [comment]
This will likely not make it in time for the v3.0.1 release. I haven't been able to look at this upstream yet and I'm having some issues with my computer where I do the compilations.

**Comment by Jacalz** [comment]
This is now fixed with [v3.0.1](https://github.com/Jacalz/rymdport/releases/tag/v3.0.1). Thanks for reporting.
