### ISSUE TITLE
See file extensions in dialog box

### ISSUE THREAD

**Issue by waldner** [Jacalz/rymdport#39]
When choosing files to send, it would be nice to be able to see not only the hidden files (for which an option exists), but also the full file names with extensions.

**Comment by Jacalz** [comment]
Hi. Thanks for opening this issue. Do you mean that you want to have the grid view show more information? There is currently an option to press a button (I have highlighted it with a red square in the image below) to switch into a list view. That option should allow you to see full filenames and extensions. 
![image](https://user-images.githubusercontent.com/25466657/171806480-ba88ddaa-2bca-4384-ad2b-7002fd353bbf.png)
![image](https://user-images.githubusercontent.com/25466657/171806290-1df42953-77d9-412f-9e43-e9e07dd4914c.png)

**Comment by waldner** [comment]
Yes, I used that option but still file extensions are not shown, see the attached image. Yes, they are shown (in very small fonts) in the file's icon, but whay I'd like is to actually see the full name shown, eg `kindle-backgrounds.zip`, `laughing-seal.jpg` etc. Thanks

![Screenshot_2022-06-03_10-42-16](https://user-images.githubusercontent.com/1726393/171820964-8da7e624-4dd8-41eb-b3b8-0c38e6daec59.png)

**Comment by Jacalz** [comment]
Ah, I see now. Thanks. It is a bit strange. Some extensions (like `.so`) is shown in my image above but I can also replicate what you are seeing. I will see about getting this fixed upstream in https://github.com/fyne-io/fyne where the issue lies but we can keep this issue open until then.

**Comment by Jacalz** [comment]
It looks like the file extensions are being ripped out here: https://github.com/fyne-io/fyne/blob/7229e889d49c81a83b0b7e09400837f67f6ddad5/dialog/fileitem.go#L66-L73. The v2.2.0 RC1 release of Fyne is happening later today, so I think that I unfortunately won't manage to squeeze this in before then but I will see what I can do.

**Comment by Jacalz** [comment]
I have now opened https://github.com/fyne-io/fyne/pull/3033 to make sure that extensions are shown in the list view but not in the grid view. This will be fixed with Fyne v2.2.0 and consequently also in the next Rymdport release. I also opened https://github.com/fyne-io/fyne/issues/3032 to track the addition of adding an option some time in the future :)
