### ISSUE TITLE
Cannot resize file picker dialog

### ISSUE THREAD

**Issue by waldner** [Jacalz/rymdport#42]
The file picker window cannot be resized. I'm aware of https://github.com/Jacalz/rymdport/issues/16, however I think not being able to resize goes against user's expectations. Also being forced to close the picker, resize the main window, then reopen the picker is cumbersome imho.

**Comment by Jacalz** [comment]
Thanks for opening this. I definitely agree that this would be a good improvement but I don't think there is much that I can do at this time.

The dialog is part of Fyne (the gui-library that I'm using) and it is a bit limited in what I can do here. There is currently no easy way to automatically refresh the dialog when the main window is refreshed.

**Comment by waldner** [comment]
A GUI toolkit which doesn't allow window resizing in 2022 sounds very strange to me, but of course it's not your fault and I take your word for it. Thanks!

**Comment by Jacalz** [comment]
No worries. They support resizing but not for the dialogs at the moment. You might want to open an issue over at https://github.com/fyne-io/fyne/issues if you have a strong opinion that it should be solved 🙂

I know that we plan to add support in Fyne for using system dialogs for Flatpak (only on Linux unfortunately) packages but I haven’t gotten around to looking at it yet.

**Comment by waldner** [comment]
Ah I see, I wasn't aware of the distinction the toolkit makes between windows and dialogs. It's not a terrible annoyance, of course, so let's wait and see if upstream comes up with the feature. Thanks again.

**Comment by Jacalz** [comment]
Thanks again for opening this. I have however thought a bit more about it and decided that it makes more sense to be fixed upstream in Fyne. I will thus close this issue for now. Do not hesitate to open more issues with suggestions, improvements or other bug reports. Every piece of feedback is greatly appreciated :)
