### ISSUE TITLE
Fails to start on Windows due to incorrect side-by-side configuration

### ISSUE THREAD

**Issue by BackSpace54** [Jacalz/rymdport#58]
### Description:
Windows version failed to start since 3.3.0RC1 with this message:
The application has failed to start because its side-by-side configuration is incorrect.  Please see the application event log or use the command-line sxstrace.exe tool for more detail.

### Steps to Reproduce:
1. Unzip rymdport-v3.3.0-rc1-windows-amd64.zip or >
2. Run rymdport.exe

### Screenshots:

N/A

### Device (please complete the following information):
- **OS:** Windows 11H2 with january 23 updates
- **Version:** 22621.1105
- **Rymdport version:** 3.3.0RC1 and 3.3.0

#### Extra information
As suggested by the error message the sxstrace.exe tool give this:
INFO: Manifest Definition Identity is (null).
Error on line 3. The value "1.0.1" of attribute "version" in element "assemblyIdentity" is invalid.
Activation context generation failed.

For info the 3.2.0 runs flawless on the same computer.

**Comment by Jacalz** [comment]
Thanks for reporting. That error does not sound good. Will see if I can get access to a Windows computer and reproduce it on my end

**Comment by jnolan7599** [comment]
@Jacalz 

_rymdport-v3.3.0-windows-amd64_ gives me a similar failure. Standing by...

**Comment by jkniiv** [comment]
Just to confirm, exactly the same happens on a Finnish language Windows 10 ver. 22H2 with January 2023 updates. Sxstrace.exe gives the following human readable log:
```
=================
Begin Activation Context Generation.
Input Parameter:
        Flags = 0
        ProcessorArchitecture = AMD64
        CultureFallBacks = fi-FI;fi;en-US;en
        ManifestPath = C:\Apps\rymdport-v3.3.0-windows-amd64\rymdport.exe
        AssemblyDirectory = C:\Apps\rymdport-v3.3.0-windows-amd64\
        Application Config File =
-----------------
INFO: Parsing Manifest File C:\Apps\rymdport-v3.3.0-windows-amd64\rymdport.exe.
        INFO: Manifest Definition Identity is (null).
        ERROR: Line 3: The value 1.0.1 of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.
```
3.2.0 runs just nicely on this same laptop.

**Comment by jkniiv** [comment]
FYI, a `go build` of 3.3.0 from source works fine in MSYS2 MinGW64 shell after I've installed all the requisites (i.e. managed to build fyne_demo first). However, the resulting executable doesn't seem to have an icon. Otherwise it runs fine.

**Comment by Jacalz** [comment]
Thanks. I think there is something weird with the data that is used to bundle in the icon and some other metadata.

Would you mind testing to see if using the fyne cmd command (at https://github.com/fyne-io/fyne/tree/master/cmd/fyne or installing using `go install fyne.io/fyne/v2/cmd/fyne@latest`) to build the binary work? You run `fyne package` (using that tool) here in the project and it will then build a packaged version with all metadata added for you. If that binary then fails to launch, I expect that there is a bug in the latest release of that tool.

I haven’t had time to look into it further myself. Quite busy this week with all the new courses starting this semester at the university.

**Comment by jkniiv** [comment]
I was able to install the fyne command as you instructed with `go install ...` and with that build the packaged version with `fyne package`. Also the stripped/release version came about simply with `fyne package --release` in the project directory. So no problem there. The executable has now an icon and some metadata, cf. a screenshot below in Finnish of the properties dialog. More importantly the executable works and transfers files AOK. :)

![image](https://user-images.githubusercontent.com/3973342/213595855-eb881c1a-aa78-4170-82d1-f74cd8c48fd2.png)

Some translation:
"Tiedoston kuvaus" -> File description
"Tyyppi" -> Type
"Sovellus" -> Executable
"Tiedoston versio" -> File version
"Tuotenimi" -> Product name
"Tuoteversio" -> Product version
"Tekijänoikeus" -> Copyright
"Koko" -> Size
"Muokkauspäivä" -> Modification date
"Kieli" -> Language
"Kielen suhteen neutraali" -> Neutral in relation to language

**Comment by Jacalz** [comment]
Thanks a lot for testing. That is good to know. I'll have a look at what I can do :)

**Comment by Jacalz** [comment]
Sorry for the wait everyone. I have still been busy. Will try to build new Windows binaries with https://github.com/fyne-io/fyne-cross (instead of https://fynelabs.com/geoffrey/ that I recently switched to using) later in the week. If those binaries work, I will get a new release out and also speak with the kind folks at Fyne Labs to see if the issue lies on their end :)

**Comment by jkniiv** [comment]
On my part I can confirm that `fyne-cross` works just fine and produces at least the amd64 binary just so that it is runnable on Windows 10. Also the icon gets set. I happened to have an Ubuntu 20.04 virtual machine with Docker (and docker compose) installed, so I proceeded to try out `fyne-cross` according to the instruction in its Github repo. It turned out it was very easy to use `fyne-cross` with the fyne examples project and also Rymdport source: just invoke `fyne-cross linux` or `fyne-cross windows` in the source directory to get packaged Linux and Windows binaries accordingly in a subdirectory called `fyne-cross`. The only difference compared to the `fyne package` method was that, at least by default, `fyne-cross` produces quite a bit less metadata than the former, cf. the following screenshot of the properties dialog:

![image](https://user-images.githubusercontent.com/3973342/214819304-be5b6da8-4993-4e76-90bf-b1049a94fe04.png)

**Comment by Jacalz** [comment]
Perfect. Thank you. Will likely get the new binaries out on Saturday :)

**Comment by Jacalz** [comment]
I have now built a new binary for Windows using fyne-cross. If this works, I will make sure to get a new v3.3.1 release out :)
[rymdport-v3.3.1-windows-amd64.zip](https://github.com/Jacalz/rymdport/files/10527105/rymdport-v3.3.1-windows-amd64.zip)

**Comment by Jacalz** [comment]
This should now be fixed with https://github.com/Jacalz/rymdport/releases/tag/v3.3.1. Thanks to everyone that has tested and helped out with this. Will make sure that the automatically built Windows builds are working for the following releases so I can avoid having to build them manually :)

**Comment by jkniiv** [comment]
Many thanks for taking care of this problem, Jacalz. :)

**Comment by Jacalz** [comment]
I'm glad to report that the automatic builds are back to working on Windows again. This means that everyone on Windows should receive in-app updates on startup (update notification and then automatic app restart if you choose to install the update) once v3.3.2 is released in a few days 🥳
