### ISSUE TITLE
Release Artifacts of v3.3.1 have wrong version number.

### ISSUE THREAD

**Issue by erdii** [Jacalz/rymdport#65]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

Heyo @Jacalz :)

The tarballs in the [v3.3.1 release](https://github.com/Jacalz/rymdport/releases/tag/v3.3.1) partially use v3.3.0 in their filenames.
This breaks the build for the binary package in the AUR since it expects the version in the filename to be correct.
 
```
==> Retrieving sources...
  -> Downloading rymdport-bin-3.3.1.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/Jacalz/rymdport/releases/download/v3.3.1/rymdport-v3.3.1-linux-amd64.tar.xz
    Aborting...
```

### Steps to Reproduce

1. go here: https://github.com/Jacalz/rymdport/releases/tag/v3.3.1
2. :eyes: 

### Rymdport version

3.3.1

### Operating System

Other (specify below)

### Operating System Version

Freebsd, Linux, macOS

**Comment by Jacalz** [comment]
Thanks for reporting. This was intended as there were no code changes but I see your point about it not being ideal. Will release v3.3.2 in the coming days so you can just skip v3.3.1 for now (or use v3.3.0 as it has the same code). I will keep this in mind for future releases :)

**Comment by Jacalz** [comment]
Should be solved with https://github.com/Jacalz/rymdport/releases/tag/v3.3.2 now. Sorry for the trouble.
