### ISSUE TITLE
Drag & Drop support

### ISSUE THREAD

**Issue by Dr-Hex** [Jacalz/rymdport#73]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Please, add ability to drag & drop files and folder onto the application's form for more easy usage.
The current open files dialog looks not friendly (no ability to insert the direct link).

### Describe the solution you'd like to see.

-

**Comment by Jacalz** [comment]
I agree that this is a great addition but it is unfortunately not possible to implement until https://github.com/fyne-io/fyne/issues/142 is supported upstream.

**Comment by Dr-Hex** [comment]
I love those modern multi-OS frameworks with 20k stars which adding such a basic features for more than 3 years :D
Thanks for information.

**Comment by Jacalz** [comment]
Hehe, yeah. We have had more important things to implement. It is close then ever as someone sent out a comment on how the backing infrastructure should be done. We basically just need to figure out a sensible API and that is the hard part. I might have a look at it myself some time in the future but I am a bit busy with studies.

**Comment by Jacalz** [comment]
This should be unblocked now that I have merged https://github.com/fyne-io/fyne/pull/3954 upstream. I'll target this for the next Rymdport release in a month or two

**Comment by Jacalz** [comment]
Support for this is now in the `next` branch ready for the next release. Will close this now.
