### ISSUE TITLE
Update dialog incorrectly notifies about new update

### ISSUE THREAD

**Issue by kirillz** [Jacalz/rymdport#76]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

Update dialog when program is updated. Click "Yes" - do nothing.

### Steps to Reproduce

1. Run application and dialog showed

### Screenshots

Hello
![image](https://user-images.githubusercontent.com/1161809/226582121-dcdbcd01-5363-4a19-a5f4-842dd9aaf047.png)
 version of app
![image](https://user-images.githubusercontent.com/1161809/226582239-42913c7f-1dae-4a26-ba14-e498d1c1f685.png)

### Rymdport version

v3.3.2

### Operating System

Windows

### Operating System Version

windows 10 x64

### Additional Information

Update dialog bugged. Ty

**Comment by Jacalz** [comment]
Hmm. That's strange. I hadn't noticed this as only release binaries have updates enabled but I can replicate the same thing on Linux. Thanks for filling the bug.

**Comment by Jacalz** [comment]
There is not a new update available to update to. I suspect that something is wrong with the update checks.

**Comment by kirillz** [comment]
Yep i think fork and add in Settings window after notifications something like "Enable update on startup" Yes No

**Comment by kirillz** [comment]
now I did a git clone and I already have version 3.3.3, although there was no release, so everything is fine with update.

**Comment by Jacalz** [comment]
> now I did a git clone and I already have version 3.3.3, although there was no release, so everything is fine with update. smiley_cat

No, it is not fixed yet. The v3.3.3 changes are just already in the `main` branch but it has not been released. It should not report that an update is available. Update checking is not enabled when you build using `go build` because you need to pass `-tags release` to enable them.

**Comment by Jacalz** [comment]
> Yes, I'm thinking of forking and adding something like "Enable update on startup" to the settings window after notifications Yes No, but I'm new to golang and couldn't find a method on Disable Update :)

Thanks. You are more than welcome to open a PR against the `next` branch (`main` is only for bug fix releases and this issue is no fixed yet). You can add it as closing #66 instead.

**Comment by Jacalz** [comment]
An update on the matter: My friends at [Fyne Labs](https://fynelabs.com/), who created the update tools that I am using, are looking into why this happens.

**Comment by Jacalz** [comment]
This will be fixed with the upcoming release in a few days.

**Comment by Jacalz** [comment]
@graphixillusion Thanks for reporting. Please open a new bug report for it though.
