### ISSUE TITLE
Make use of new List widget item refresh

### ISSUE THREAD

**Issue by Jacalz** [Jacalz/rymdport#99]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

We are currently refreshing the whole list (it probably only updates the visible items but anyhow) when we only have changed one item. Fyne v2.4.0 has a new API for refreshing an item at a specific ID. Using that would improve the performance for refreshing items.

### Describe the solution you'd like to see.

We might want to keep track of the item id in the item struct and have it call refresh item. Deleting an item would have to update all of the item ids and keep some kind of lock to make sure that we don't refresh the wrong item (or crash).

**Comment by GalihFajar** [comment]
Hey @Jacalz I just worked on this one, didn't realize you were assigned 😅 .  Feel free to drop my PR.

**Comment by Jacalz** [comment]
Its fine. I'll remove myself from the issue :)

**Comment by Jacalz** [comment]
Like I stated on the PR, the approach isn't the right one unfortunately and it is a bit complicated to get right (why I removed the good-first-issue) tag. If you want me to take this on instead I can do that.

**Comment by GalihFajar** [comment]
Sure, I'll withdraw the PR instead. I didn't really get the expected solution

**Comment by Jacalz** [comment]
Sure. I hope you didn't take any offence. I'm very glad of your work and finally seeing some contributions here :)

**Comment by GalihFajar** [comment]
surely none taken 😆

**Comment by Jacalz** [comment]
I've fixed this with https://github.com/Jacalz/rymdport/commit/e546ab5d5753ea6e4cefbf3ced4f0f94f6567f91 initially. Might need some more locking but I'd have to think about that to avoid introducing potential for deadlocks.
